# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.FloatField()),
                ('poids', models.FloatField()),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
