# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
