# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.AlterField(
            model_name='produit',
            name='categories',
            field=models.ManyToManyField(to='produits.Categorie'),
        ),
    ]
