# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import produits.models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_auto_20160510_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=produits.models.get_image_filename, verbose_name='Image')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='produits.Produit')),
            ],
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ('categorie',)},
        ),
    ]
