# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_auto_20160510_1441'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
