# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_auto_20160510_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='/home/zspirit/Projects/catalogue/static/produits/static/uploads/%Y/%m/%d/', verbose_name='Image'),
        ),
    ]
